# Generated by Django 5.0.3 on 2024-03-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_shippingaddress_shippingprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../default_profile_tvknyo', upload_to=''),
        ),
    ]
